# Generated by Django 5.0.7 on 2024-07-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_bio',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.course'),
        ),
    ]
